# Generated by Django 2.2.3 on 2019-07-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refugee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_from_refugee',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
