# Generated by Django 2.2.3 on 2019-07-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refugee', '0002_story_is_from_refugee'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
