# Generated by Django 2.2.3 on 2019-07-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refugee', '0003_story_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='image_url',
            field=models.TextField(blank=True),
        ),
    ]
